### ISSUE TITLE
运行taichi-nerfs时候的错误

### ISSUE THREAD

**Issue by LilFoxProgramer** [taichi-dev/taichi-nerfs#21]
[Taichi] version 1.6.0, llvm 15.0.4, commit c8a31d35, linux, python 3.7.12
/opt/conda/lib/python3.7/site-packages/torch/amp/autocast_mode.py:202: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from modules.networks import TaichiNGP
  File "/kaggle/working/taichi-nerfs/modules/networks.py", line 10, in <module>
    from .hash_encoder import HashEncoder
  File "/kaggle/working/taichi-nerfs/modules/hash_encoder.py", line 7, in <module>
    from .utils import (data_type, ti2torch, ti2torch_grad, ti2torch_grad_vec,
  File "/kaggle/working/taichi-nerfs/modules/utils.py", line 91, in <module>
    def morton3D_invert_kernel(indices: ti.types.ndarray(field_dim=1),
  File "/opt/conda/lib/python3.7/site-packages/taichi/types/ndarray_type.py", line 88, in __init__
    "The field_dim argument for ndarray type is already deprecated. Please use ndim instead."
ValueError: The field_dim argument for ndarray type is already deprecated. Please use ndim instead.

请问需要修改什么解决报错

**Comment by erizmr** [comment]
更新了一版，尝试重新pull一下最新的main再试试？

**Comment by loonggi** [comment]
这一般是cuda或者cudatoolkit没装对的问题。另外要注意一下，本地的cuda和虚拟环境里的cuda调用问题。

**Comment by ailzhang** [comment]
This issue should have been resolved on taichi-nerfs master, closing this issue but please feel free to reopen if you have followup questions!
