### ISSUE TITLE
error: Assertion failure: prealloc_size <= total_mem when I try to train the Lego

### ISSUE THREAD

**Issue by 52wdWPF** [taichi-dev/taichi-nerfs#38]
RTX3050 mobile,  Ubuntu 22.04.2 LTS x86_64 

I don't know how to solve this problem, I try to change the patch_size into 2048 even 512 in train_nsvf_lego.sh and train.py but it can't work for me.

What can I do next.

![Screenshot from 2023-04-20 00-36-17](https://user-images.githubusercontent.com/95855323/233142395-0b2b7099-1f60-4579-928a-08b86a9beb3f.png)

./scripts/train_nsvf_lego.sh
[Taichi] version 1.7.0, llvm 15.0.4, commit 40ba02a3, linux, python 3.10.6
[Taichi] Starting on arch=cuda
[E 04/20/23 00:28:48.932 11717] [llvm_runtime_executor.cpp:materialize_runtime@570] Assertion failure: prealloc_size <= total_mem

Traceback (most recent call last):
  File "/home/zzz/lec/taichi-nerfs/train.py", line 279, in <module>
    taichi_init(hparams)
  File "/home/zzz/lec/taichi-nerfs/train.py", line 273, in taichi_init
    ti.init(**taichi_init_args)
  File "/home/zzz/.local/lib/python3.10/site-packages/taichi/lang/misc.py", line 455, in init
    impl.get_runtime().prog.materialize_runtime()
RuntimeError: [llvm_runtime_executor.cpp:materialize_runtime@570] Assertion failure: prealloc_size <= total_mem

**Comment by bobcao3** [comment]
You would need to find the `ti.init` statement and then lower the memory allocation number.

**Comment by 52wdWPF** [comment]
yes! I solve this (last night, but my roommate have to sleep so I go to sleep too) by modify the 

> device_memory_GB to 1.0 that is work

![image](https://user-images.githubusercontent.com/95855323/233261098-b4972a0f-bbd8-49e2-9718-744714e7c5bd.png)

but it have another error for me!

![image](https://user-images.githubusercontent.com/95855323/233262551-ff771894-73b1-42db-90df-940b0f630eb5.png)
